# Generated by Django 5.2.11 on 2026-04-12 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperslotexception',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.order'),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.address'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='service_category',
            field=models.ManyToManyField(blank=True, to='task.servicecategory'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerverification',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='account.serviceproviderprofile'),
        ),
        migrations.AddField(
            model_name='providerpayoutmethod',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to='account.serviceproviderprofile'),
        ),
        migrations.AddField(
            model_name='helperweeklyavailability',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='account.serviceproviderprofile'),
        ),
        migrations.AddField(
            model_name='helperstrike',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='account.serviceproviderprofile'),
        ),
        migrations.AddField(
            model_name='helperspecialdate',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_dates', to='account.serviceproviderprofile'),
        ),
        migrations.AddField(
            model_name='helperslotexception',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_exceptions', to='account.serviceproviderprofile'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_payment_per_user'),
        ),
        migrations.AddConstraint(
            model_name='providerpayoutmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('provider',), name='unique_default_payout_per_provider'),
        ),
        migrations.AddIndex(
            model_name='helperweeklyavailability',
            index=models.Index(fields=['provider', 'day'], name='account_hel_provide_4ac175_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helperweeklyavailability',
            unique_together={('provider', 'day')},
        ),
    ]
