# Generated by Django 5.2.11 on 2026-03-26 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='service_category',
            field=models.ManyToManyField(blank=True, to='task.servicecategory'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerverification',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='account.serviceproviderprofile'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
