# Generated by Django 6.0.1 on 2026-01-24 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='service_category',
            field=models.ManyToManyField(blank=True, null=True, to='task.servicecategory'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
