# Generated by Django 6.0.4 on 2026-04-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user_type',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Administrator')], default='USER', max_length=30),
        ),
    ]
