# Generated by Django 6.0.4 on 2026-07-19 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('task', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='strike_count',
        ),
        migrations.AddField(
            model_name='helperstrike',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='task.order'),
        ),
        migrations.AddField(
            model_name='helperstrike',
            name='related_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='task.orderchangesrequest'),
        ),
        migrations.AlterField(
            model_name='helperstrike',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='account.serviceproviderprofile'),
        ),
    ]
