# Generated by Django 5.2.11 on 2026-02-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_address_address_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='default_user',
            new_name='default_profile',
        ),
    ]
