# Generated by Django 6.0.4 on 2026-04-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_activitylog_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='user_type',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('PROVIDER', 'Provider')], max_length=30, null=True),
        ),
    ]
