# Generated by Django 6.0.1 on 2026-01-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('SIGNUP', 'Signup'), ('VERIFY', 'Verify'), ('RESET_PASSWORD', 'Reset Password')], max_length=20),
        ),
    ]
