# Generated by Django 5.2.11 on 2026-03-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_serviceproviderprofile_office_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='helper_profile_status',
            field=models.BooleanField(default=False),
        ),
    ]
