# Generated by Django 6.0.1 on 2026-01-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_otp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
