# Generated by Django 5.2.11 on 2026-03-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_helper_profile_status'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='service_subcategory',
            field=models.ManyToManyField(blank=True, to='task.servicesubcategory'),
        ),
    ]
