# Generated by Django 6.0.4 on 2026-04-19 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_activitylog_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_helpers', to='account.customerprofile')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_customers', to='account.serviceproviderprofile')),
            ],
            options={
                'unique_together': {('customer', 'helper')},
            },
        ),
    ]
