# Generated by Django 5.2.11 on 2026-02-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_default_user_user_default_profile'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'profile_type', 'object_id'), name='unique_default_address_per_profile'),
        ),
    ]
