# Generated by Django 5.2.11 on 2026-03-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_serviceproviderprofile_service_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerScreenSlide',
        ),
        migrations.DeleteModel(
            name='SignUpSlider',
        ),
    ]
