# Generated by Django 5.2.11 on 2026-03-29 21:43

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_customerscreenslide_delete_signupslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('method_type', models.CharField(choices=[('CARD', 'Card'), ('BANK', 'Bank'), ('WALLET', 'Wallet')], max_length=30)),
                ('payment_token', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('method_data', models.JSONField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderPayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('BANK', 'Bank'), ('WALLET', 'Wallet')], default='BANK', max_length=50)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_token', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('method_data', models.JSONField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to='account.serviceproviderprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
