# Generated by Django 6.0.4 on 2026-04-21 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_helperweeklyavailability_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperwallet',
            name='provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='account.serviceproviderprofile'),
        ),
    ]
