# Generated by Django 6.0.1 on 2026-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_address_user'),
        ('task', '0002_alter_servicecategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='service_category',
            field=models.ManyToManyField(blank=True, null=True, to='task.servicecategory'),
        ),
    ]
