# Generated by Django 5.2.11 on 2026-03-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customerpaymentmethod_providerpayoutmethod_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customerpaymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_payment_per_user'),
        ),
        migrations.AddConstraint(
            model_name='providerpayoutmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('provider',), name='unique_default_payout_per_provider'),
        ),
    ]
