# Generated by Django 6.0.1 on 2026-01-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customerscreenslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='need_notify',
            field=models.BooleanField(default=False),
        ),
    ]
