# Generated by Django 6.0.1 on 2026-01-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_address_object_id_address_profile_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_user',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('PROVIDER', 'Provider')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Administrator')], default='USER', max_length=30),
        ),
    ]
