# Generated by Django 6.0.1 on 2026-01-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_activitylog_need_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='entity_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
