# Generated by Django 6.0.4 on 2026-04-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_activitylog_status_alter_activitylog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='total_profile_view',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
