# Generated by Django 6.0.1 on 2026-01-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_activitylog_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVE', 'Deactive'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=30),
        ),
        migrations.CreateModel(
            name='ProviderVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('PASSPORT', 'Passport'), ('NID', 'Nid'), ('DRIVING_LICENSE', 'Driving License')], max_length=20, null=True)),
                ('document', models.ImageField(blank=True, null=True, upload_to='user/verification/')),
                ('is_verified', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='account.serviceproviderprofile')),
            ],
        ),
    ]
