# Generated by Django 6.0.4 on 2026-04-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_serviceproviderprofile_total_profile_view'),
        ('task', '0008_alter_paymenttransaction_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperslotexception',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_exceptions', to='task.order'),
        ),
    ]
