# Generated by Django 6.0.1 on 2026-01-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_serviceproviderprofile_is_verified_alter_user_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerverification',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REVIEW', 'Review'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='REVIEW', max_length=20),
        ),
    ]
