# Generated by Django 6.0.4 on 2026-04-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_helperslotexception_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperslotexception',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
