# Generated by Django 6.0.1 on 2026-01-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_providerverification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'En'), ('zh', 'Zh')], default='en', max_length=10),
        ),
    ]
