# Generated by Django 6.0.4 on 2026-04-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_helperslotexception_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='metadata',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
