# Generated by Django 5.2.11 on 2026-05-18 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_customerprofile_options_and_more'),
        ('task', '0012_delete_adminwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='serviceproviderprofile',
            index=models.Index(fields=['is_verified'], name='service_pro_is_veri_d44561_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceproviderprofile',
            index=models.Index(fields=['availability_status'], name='service_pro_availab_4fa2bb_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceproviderprofile',
            index=models.Index(fields=['rating'], name='service_pro_rating_839938_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceproviderprofile',
            index=models.Index(fields=['account_status'], name='service_pro_account_a8edcf_idx'),
        ),
        migrations.AlterModelTable(
            name='serviceproviderprofile',
            table='service_provider_profiles',
        ),
    ]
