# Generated by Django 6.0.4 on 2026-05-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_serviceproviderprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerverification',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerverification',
            name='document_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
