# Generated by Django 6.0.4 on 2026-05-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_providerverification_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerverification',
            name='full_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
