# Generated by Django 5.2.11 on 2026-03-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_profile_type',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('PROVIDER', 'Provider')], max_length=50, null=True),
        ),
    ]
