# Generated by Django 6.0.4 on 2026-04-22 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='ticketreply',
            options={'ordering': ['created_at']},
        ),
    ]
