# Generated by Django 5.2.11 on 2026-03-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customerscreenslide_signupslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOfferVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='DISCOUNT VOUCHER', max_length=100, null=True)),
                ('code', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upto_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
