# Generated by Django 6.0.1 on 2026-01-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='title',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='object_id',
            new_name='entity_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='content_type',
            new_name='entity_type',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='data',
            new_name='metadata',
        ),
    ]
