# Generated by Django 6.0.1 on 2026-01-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notify', '0002_rename_title_notification_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
