# Generated by Django 6.0.4 on 2026-04-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notify', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='profile',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('PROVIDER', 'Provider')], max_length=20, null=True),
        ),
    ]
