# Generated by Django 6.0.1 on 2026-01-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notify', '0002_notification_content_type_notification_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
