# Generated by Django 6.0.4 on 2026-04-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notify', '0004_notification_message_notification_notification_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='metadata',
        ),
    ]
