# Generated by Django 6.0.4 on 2026-04-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notify', '0005_remove_notification_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='received',
            new_name='receiver',
        ),
    ]
