# Generated by Django 6.0.4 on 2026-04-29 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notify', '0006_rename_received_notification_receiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='type',
            new_name='message_type',
        ),
    ]
