# Generated by Django 6.0.4 on 2026-04-30 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notify', '0007_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customoffer',
            old_name='reference_object',
            new_name='changes_object',
        ),
    ]
