# Generated by Django 6.0.4 on 2026-06-01 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notify', '0007_alter_chatmessage_options_and_more'),
        ('task', '0012_delete_adminwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FILE', 'File'), ('OFFER', 'Offer'), ('ORDER_CREATED', 'Order Created'), ('ORDER_UPDATED', 'Order Updated'), ('ORDER_STATUS', 'Order Status'), ('ORDER_CHANGE_REQUEST', 'Order Change Request')], default='TEXT', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FILE', 'File'), ('OFFER', 'Offer'), ('ORDER_CREATED', 'Order Created'), ('ORDER_UPDATED', 'Order Updated'), ('ORDER_STATUS', 'Order Status'), ('ORDER_CHANGE_REQUEST', 'Order Change Request')], default='ORDER_CREATED', max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='chat_notify.chatmessage')),
                ('order_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.order')),
                ('reference_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.orderchangesrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomOffer',
        ),
    ]
