# Generated by Django 6.0.4 on 2026-06-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notify', '0008_alter_chatmessage_message_type_chatevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatevent',
            name='event_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FILE', 'File'), ('EVENT', 'event'), ('ORDER_CREATED', 'Order Created'), ('ORDER_UPDATED', 'Order Updated'), ('ORDER_STATUS', 'Order Status'), ('ORDER_CHANGE_REQUEST', 'Order Change Request')], default='ORDER_CREATED', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FILE', 'File'), ('EVENT', 'event'), ('ORDER_CREATED', 'Order Created'), ('ORDER_UPDATED', 'Order Updated'), ('ORDER_STATUS', 'Order Status'), ('ORDER_CHANGE_REQUEST', 'Order Change Request')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
