# Generated by Django 6.0.4 on 2026-06-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notify', '0009_alter_chatevent_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatevent',
            name='event_type',
            field=models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_COUNTER', 'Order Counter'), ('ORDER_UPDATED', 'Order Updated'), ('ORDER_STATUS', 'Order Status'), ('ORDER_CANCEL', 'Order Cancel'), ('ORDER_COMPLETEL', 'Order Complete'), ('ORDER_WORK_START', 'Order Work Start'), ('ORDER_HOUR_SET', 'Order Hour Set'), ('ORDER_CHANGE_REQUEST', 'Order Change Request')], default='ORDER_CREATED', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FILE', 'File'), ('EVENT', 'event')], default='TEXT', max_length=20),
        ),
    ]
