# Generated by Django 6.0.1 on 2026-01-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_adminwallet_remove_wallettransaction_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallet',
            name='payment_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='action',
            field=models.CharField(blank=True, choices=[('ORDER_PAYMENT', 'Order Payment'), ('PAYMENT_HOLD', 'Payment Hold'), ('SEND_PROVIDER', 'Send Provider'), ('REFUND_CUSTOMER', 'Refund Customer')], max_length=50, null=True),
        ),
    ]
