# Generated by Django 6.0.1 on 2026-01-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_adminwallet_payment_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='payment_method_information',
            new_name='payment_information',
        ),
    ]
