# Generated by Django 6.0.4 on 2026-07-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_change_action',
            field=models.CharField(choices=[('PROVIDER_TIME_CHANGE_REQUEST_SEND', 'Provider Time Change Request Send'), ('CUSTOMER_TIME_CHANGE_REQUEST_SEND', 'Customer Time Change Request Send'), ('PROVIDER_COUNTER_SEND', 'Provider Counter Send'), ('CUSTOMER_COUNTER_SEND', 'Customer Counter Send'), ('NO_ACTION', 'No Action')], default='NO_ACTION', max_length=40),
        ),
    ]
