# Generated by Django 6.0.1 on 2026-01-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
