# Generated by Django 5.2.11 on 2026-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('MARKETPLACE', 'Marketplace'), ('DIRECT', 'Direct')], default='MARKETPLACE', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='budget_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='budget_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
