# Generated by Django 6.0.4 on 2026-07-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_order_order_change_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderchangesrequest',
            name='perform_by',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('PROVIDER', 'Provider')], default='PROVIDER', max_length=20),
        ),
    ]
