# Generated by Django 6.0.1 on 2026-01-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('DISBUSMENT', 'Disbusment'), ('PAID_TO_PROVIDER', 'Paid To Provider'), ('CANCELLED', 'Cancelled'), ('REFUND', 'Refund')], default='UNPAID', max_length=20),
        ),
    ]
