# Generated by Django 5.2.11 on 2026-04-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_order_subcategory_order_accepted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderchangesrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='orderchangesrequest',
            name='status',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('DECLINED', 'Declined'), ('NO_RESPONSE', 'No Response')], default='NO_RESPONSE', max_length=20),
        ),
    ]
