# Generated by Django 5.2.11 on 2026-02-25 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_servicesubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='task.servicecategory'),
        ),
    ]
