# Generated by Django 6.0.1 on 2026-01-17 20:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_servicecategory_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobRequest',
            new_name='TaskRequest',
        ),
    ]
