# Generated by Django 6.0.4 on 2026-04-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_orderchangesrequest_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='working_hour',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
