# Generated by Django 6.0.1 on 2026-01-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ACCEPT', 'Accept'), ('CONFIRM', 'Confirm'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PARTIAL_COMPLETE', 'Partial Complete'), ('CANCELLED', 'Cancelled'), ('REFUND', 'Refund')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('TERMINATE', 'Terminate'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
