# Generated by Django 6.0.4 on 2026-07-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_order_cancel_at_orderchangesrequest_perform_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_change_action',
            field=models.CharField(choices=[('PROVIDER_TIME_CHANGE_REQUEST_SEND', 'Provider Time Change Request Send'), ('CUSTOMER_TIME_CHANGE_REQUEST_SEND', 'Customer Time Change Request Send'), ('PROVIDER_COUNTER_SEND', 'Provider Counter Send'), ('CUSTOMER_COUNTER_SEND', 'Customer Counter Send'), ('PROVIDER_CANCEL_REQUEST_SEND', 'Provider Cancel Request Send'), ('CUSTOMER_CANCEL_REQUEST_SEND', 'Customer Cancel Request Send'), ('NO_ACTION', 'No Action')], default='NO_ACTION', max_length=40),
        ),
        migrations.AlterField(
            model_name='orderchangesrequest',
            name='perform_by',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('PROVIDER', 'Provider')], max_length=20, null=True),
        ),
    ]
