# Generated by Django 6.0.1 on 2026-01-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_jobrequest_taskrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetask',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
