# Generated by Django 6.0.1 on 2026-01-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_delete_order'),
        ('task', '0004_alter_servicetask_lat_alter_servicetask_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetask',
            name='category',
        ),
        migrations.RemoveField(
            model_name='servicetask',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='taskrequest',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskrequest',
            name='provider',
        ),
        migrations.DeleteModel(
            name='ServicePrototype',
        ),
        migrations.DeleteModel(
            name='ServiceTask',
        ),
        migrations.DeleteModel(
            name='TaskRequest',
        ),
    ]
