# Generated by Django 6.0.4 on 2026-04-21 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_helperweeklyavailability_day'),
        ('task', '0004_alter_order_working_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewandrating',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_reviews', to='account.customerprofile'),
        ),
        migrations.AlterField(
            model_name='reviewandrating',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_reviews', to='account.serviceproviderprofile'),
        ),
    ]
