# Generated by Django 5.2.11 on 2026-02-25 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_address_unique_default_address_per_profile'),
        ('task', '0004_order_subcategory_alter_order_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrefundrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to='account.customerprofile'),
        ),
        migrations.AlterField(
            model_name='orderrefundrequest',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_request', to='task.order'),
        ),
    ]
