# Generated by Django 6.0.1 on 2026-01-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_order_status_alter_orderrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_OTP',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('DISBURSEMENT', 'Disbursement'), ('PAID_TO_PROVIDER', 'Paid To Provider'), ('CANCELLED', 'Cancelled'), ('REFUND', 'Refund')], default='UNPAID', max_length=20),
        ),
    ]
