# Generated by Django 5.2.11 on 2026-02-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_orderrefundrequest_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ACCEPT', 'Accept'), ('CONFIRM', 'Confirm'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PARTIAL_COMPLETE', 'Partial Complete'), ('CANCELLED', 'Cancelled'), ('REFUND_REQUEST', 'Refund Request'), ('REFUND', 'Refund')], default='ACTIVE', max_length=20),
        ),
    ]
