# Generated by Django 6.0.4 on 2026-04-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_reviewandrating_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewandrating',
            old_name='created',
            new_name='created_at',
        ),
    ]
