# Generated by Django 6.0.1 on 2026-01-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_order_confirmation_otp_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('DISBURSEMENT', 'Disbursement'), ('CANCELLED', 'Cancelled'), ('REFUND', 'Refund')], default='UNPAID', max_length=20),
        ),
    ]
