# Generated by Django 6.0.1 on 2026-01-26 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewandrating',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_reiview', to='task.order'),
        ),
    ]
