# Generated by Django 6.0.4 on 2026-04-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_paymenttransaction_customer_paymenttransaction_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='entity_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
