# Generated by Django 6.0.1 on 2026-01-19 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_orderrequest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='task.order'),
        ),
    ]
