# Generated by Django 5.2.11 on 2026-02-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_order_lat_alter_order_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True),
        ),
    ]
