# Generated by Django 6.0.4 on 2026-04-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_paymenttransaction_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefundrequest',
            name='order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPT', 'Accept'), ('CONFIRM', 'Confirm'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PARTIAL_COMPLETE', 'Partial Complete'), ('CANCELLED', 'Cancelled'), ('CANCELLATION_REQUEST', 'Cancellation Request'), ('REFUND_REQUEST', 'Refund Request'), ('REFUND', 'Refund')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderchangesrequest',
            name='changes_type',
            field=models.CharField(choices=[('TIME', 'Time'), ('DATE', 'Date'), ('TIME_AND_DATE', 'Time And Date'), ('AMOUNT', 'Amount'), ('COUNTER', 'Counter'), ('SET_HOUR', 'Set Hour'), ('CANCEL', 'Cancel')], default='AMOUNT', max_length=30),
        ),
    ]
