# Generated by Django 6.0.1 on 2026-01-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_adminwallet_alter_reviewandrating_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
