# Generated by Django 6.0.4 on 2026-04-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_orderrefundrequest_order_amount_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='provider',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='profile',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('PROVIDER', 'Provider')], max_length=15, null=True),
        ),
    ]
