# Generated by Django 6.0.1 on 2026-01-20 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_default_user_alter_user_role'),
        ('task', '0009_alter_orderrequest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_customer', to='account.customerprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_provider', to='account.serviceproviderprofile'),
        ),
    ]
