# Generated by Django 6.0.4 on 2026-04-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_remove_paymenttransaction_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPT', 'Accept'), ('CONFIRM', 'Confirm'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CANCELLATION_REQUEST', 'Cancellation Request'), ('REFUND_REQUEST', 'Refund Request'), ('REFUND', 'Refund')], default='PENDING', max_length=20),
        ),
    ]
