# Generated by Django 6.0.1 on 2026-01-20 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_default_user_alter_user_role'),
        ('task', '0010_alter_order_customer_alter_order_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('ACCEPT', 'Accept'), ('HIRIED', 'Hiried'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PARTIAL_COMPLETE', 'Partial Complete'), ('CANCELLED', 'Cancelled'), ('REFUND', 'Refund')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_order', to='account.serviceproviderprofile'),
        ),
    ]
