# Generated by Django 5.2.11 on 2026-05-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminWallet',
        ),
    ]
